version: '3.8'

services:
  pomodoro-app:
    build: .
    ports:
      - "8080:8080"
    container_name: pomodoro-timer
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes: []
      # Optional: Mount for development (uncomment to enable live reload)
      # - ./:/app
      # - /app/node_modules
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080 > /dev/null 2>&1 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 